services:
  db:
    image: postgres:18
    container_name: postgress
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgressRailForge
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgress
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgressRailForge -d postgress"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - railForge_network

volumes:
  pgdata:

networks:
  railForge_network:
    name: railForge_network
